pull_request_rules:
  - name: Automatic merge of Snyk dependency upgrades
    conditions:
      - "author=snyk-bot"
      - "-conflict"
      - "status-success=continuous-integration/travis-ci/pr"
      - "status-success=continuous-integration/travis-ci/push"
      - "status-success=security/snyk (lukemnet)"
      - "status-success=Summary"
    actions:
      merge:
        method: squash
        strict: true
