env:
  global:
    - CC_TEST_REPORTER_ID=$CC_TEST_REPORTER_ID

language: node_js
os: linux
dist: bionic

node_js:
  - '10'
  - '12'
  - '14'
  - '15'

notifications:
  email:
    on_failure: change
    on_success: never

install:
  - npm install
  - npm install -g codecov

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - npm run build
  - codecov

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
