environment:
  matrix:
    - nodejs_version: 'lts'
    - nodejs_version: 'Current'

platform:
  - x64

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm run build

build: off
