services:
  sc2-api-service:
    container_name: sc2-api-service
    build:
      context: .
      target: development
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - ${SAS_APP_PORT}:${SAS_APP_PORT}
    command: npm run start:dev
    env_file: .env
    depends_on:
      - redis
      - bnet-auth-service

  redis:
    image: 'redis:alpine'
    ports:
      - ${SAS_REDIS_PORT}:${SAS_REDIS_PORT}

  bnet-auth-service:
    image: 'sc2pte/bnet-auth-service:2'
    ports:
      - 3001:3001
